b'locode\x00'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'locode\x00'
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'iata\x00\x00\x00'
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'locode\x00'
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'iata\x00\x00\x00'
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'locode\x00'
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'iata\x00\x00\x00'
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
b'geoname'
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 107, in start_search_in_file
    amount=amount)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 187, in search_in_file
    save_entrie(domain, location_found, loc_found_file)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 129, in save_entrie
    util.json_dump(entries, entrie_file)
  File "/data/rdns-parse/src/data_processing/util.py", line 115, in json_dump
    indent=indent)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 420, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 430, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/data/rdns-parse/src/data_processing/util.py", line 80, in json_object_encoding
    raise TypeError('Object not handled by the JSON encoding function')
TypeError: Object not handled by the JSON encoding function
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 238, in <module>
    main()
  File "/data/rdns-parse/src/find_and_evaluate/find_locations_with_trie.py", line 85, in main
    'rb') as popular_file:
FileNotFoundError: [Errno 2] No such file or directory: 'popular_labels_found_0.pickle'
